name: Continuous Integration

on:
  push:

  workflow_dispatch:

jobs:
  fix-code-style:
    name: Fix code style
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Format code
      uses: aglipanci/laravel-pint-action@2.3.0

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: >
          chore: fix code style

  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    needs: fix-code-style
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: curl, exif, fileinfo, gd, intl, mbstring, mysqli, openssl, pdo_mysql, pdo_sqlite, sqlite3, xsl

    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress

    - name: Execute tests
      run: php artisan test --parallel
