name: Check & fix styling

on: 
  push:
    branches:
      - main
    paths: 
      - '**/**'
      - '!README.md'
      - '!.github/**'

  pull_request: 
    branches: 
      - main
    paths: 
      - '**/**'
      - '!README.md'
      - '!.github/**'

  workflow_dispatch:

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Fix styling issues
        uses: aglipanci/laravel-pint-action@2.3.0

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
    
    outputs:
      pint_completed: true
