name: Run tests

on:
  push:
    paths: 
      - '**/**'
      - '!README.md'
      - '!.github/**'

  pull_request: 
    branches: 
      - main    
    paths: 
      - '**/**'
      - '!README.md'
      - '!.github/**'

  workflow_run: 
    workflows:
      - Check & fix styling
    types:
      - completed

  workflow_dispatch:


jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@2.27.1
      with:
        php-version: '8.1'
        extensions: curl, exif, fileinfo, gd, intl, mbstring, mysqli, openssl, pdo_mysql, pdo_sqlite, sqlite3, xsl

    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress
      
    - name: Setup directory permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Generate key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate

    - name: Seed database
      run: php artisan db:seed
      
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test --compact
